---
created: '2021-03-09T19:19:09.909153Z'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
app-depth-1:
  hash: "59c0434e3624d23495e047f18d5615c5"
  tree_label: "log::__private_api_log"
  component:
    app-depth-1*
      exception*
        stacktrace*
          frame*
            function*
              "log::__private_api_log"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-2:
  hash: "8cd9c779e1522f718e9270004d2029ed"
  tree_label: "log_demo::main"
  component:
    app-depth-2*
      exception*
        stacktrace*
          frame*
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
          frame*
            function*
              "sentry::integrations::log::Logger::log"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-3:
  hash: "7b1c864b21801cc624a3734761cfbc48"
  tree_label: "std::rt::lang_start::{{closure}}"
  component:
    app-depth-3*
      exception*
        stacktrace*
          frame*
            function*
              "std::rt::lang_start::{{closure}}"
          frame*
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
          frame*
            function*
              "sentry::integrations::log::Logger::log"
          frame*
            function*
              "sentry::hub::Hub::with_active"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-4:
  hash: "8484da08545a2177db5f2d6cc56ef47a"
  tree_label: "std::panicking::try::do_call"
  component:
    app-depth-4*
      exception*
        stacktrace*
          frame*
            function*
              "std::panicking::try::do_call"
          frame*
            function*
              "std::rt::lang_start::{{closure}}"
          frame*
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
          frame*
            function*
              "sentry::integrations::log::Logger::log"
          frame*
            function*
              "sentry::hub::Hub::with_active"
          frame*
            function*
              "sentry::hub::Hub::with"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-5:
  hash: "88d63e9701c93e98832eb50d7e5e9d4a"
  tree_label: "___rust_maybe_catch_panic"
  component:
    app-depth-5*
      exception*
        stacktrace*
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame*
            function*
              "std::panicking::try::do_call"
          frame*
            function*
              "std::rt::lang_start::{{closure}}"
          frame*
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
          frame*
            function*
              "sentry::integrations::log::Logger::log"
          frame*
            function*
              "sentry::hub::Hub::with_active"
          frame*
            function*
              "sentry::hub::Hub::with"
          frame*
            function*
              "sentry::hub::Hub::with_active::{{closure}}"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-max:
  hash: "00719910980352c06ba93641057012e0"
  tree_label: "_main"
  component:
    app-depth-max*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame*
            function*
              "std::rt::lang_start"
          frame*
            function*
              "std::rt::lang_start_internal"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame*
            function*
              "std::panicking::try::do_call"
          frame*
            function*
              "std::rt::lang_start::{{closure}}"
          frame*
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
          frame*
            function*
              "sentry::integrations::log::Logger::log"
          frame*
            function*
              "sentry::hub::Hub::with_active"
          frame*
            function*
              "sentry::hub::Hub::with"
          frame*
            function*
              "sentry::hub::Hub::with_active::{{closure}}"
          frame
            function (ignored unknown function)
              "<unknown>"
          frame
            function (ignored unknown function)
              "<redacted>"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system:
  hash: "00719910980352c06ba93641057012e0"
  tree_label: "_main"
  component:
    system*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame*
            function*
              "std::rt::lang_start"
          frame*
            function*
              "std::rt::lang_start_internal"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame*
            function*
              "std::panicking::try::do_call"
          frame*
            function*
              "std::rt::lang_start::{{closure}}"
          frame*
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
          frame*
            function*
              "sentry::integrations::log::Logger::log"
          frame*
            function*
              "sentry::hub::Hub::with_active"
          frame*
            function*
              "sentry::hub::Hub::with"
          frame*
            function*
              "sentry::hub::Hub::with_active::{{closure}}"
          frame
            function (ignored unknown function)
              "<unknown>"
          frame
            function (ignored unknown function)
              "<redacted>"
        type (ignored because exception is synthetic)
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
